#!/usr/bin/env python
import rospy
import pyturtlebot
import numpy as np

robot = pyturtlebot.get_robot()
#robot.move_distance(1.0)
robot.turn_angle(np.pi)

r = rospy.Rate(100)
while not rospy.is_shutdown():
    r.sleep()
